### ISSUE TITLE
Mcpe bedrock 

### ISSUE THREAD

**Issue by oguz25** [EReaXe/Gelismis-Minecraft-MOD-PACK#1]
Mcpe için birşeyler yapabilir misiniz acaba ?

**Comment by EReaXe** [comment]
**Bedrock sürümü için sadece texture pack mevcut. Bu modlar Java için yapıldığı için malesef Bedrock desteği bulunmuyor!**

[Discord](https://discord.gg/luser)

**Comment by oguz25** [comment]
teşekkür ederim :)

> **Bedrock sürümü için sadece doku paketi mevcuttur. Bu modlar Java için sevilmek için Bedrock Gelmeyecek!**
> 
> [anlaşmazlık](https://discord.gg/luser)
